### ISSUE TITLE
support for mega2560 ?

### ISSUE THREAD

**Issue by TechnicsUser** [sekdiy/CoreSensors#3]
support for mega2560 ?

**Comment by sekdiy** [comment]
Partially.

The CoreSensors library offers voltage and temperature measurement.
The ATmega2560 supports voltage measurement, but not temperature.

According to the [datasheet](http://www.atmel.com/Images/Atmel-2549-8-bit-AVR-Microcontroller-ATmega640-1280-1281-2560-2561_datasheet.pdf) (figure 26-1 on page 269) the ATmega2560 offers a second internal voltage reference instead of i.e. the ATmega328's thermal diode. So the ATmega2560 unfortunately lacks the hardware required to measure internal temperature (a featured in this library).
